// samples/react/src/components/ProfileForm.js
import React, { useRef, useEffect, useState } from 'react'

const ProfileForm = () => {
  const overlayMenuRef = useRef(null);

  const [job, setJob] = useState('');

  const handleClickJob = () => {
    if(overlayMenuRef.current) {
      overlayMenuRef.current.opened = true;
    }
  }

  useEffect(() => {
    const jobPanel = document.getElementById('jobPanel');
    const { current: overlayMenu } = overlayMenuRef
    if(overlayMenu) {
      overlayMenu.positionTarget = jobPanel;
      overlayMenu.parentElement.addEventListener('item-trigger', (e) => {
        const value = e.detail.value;
        if(value) {
          setJob(value);
          overlayMenu.opened = false;
        }
      });
    }
  }, [overlayMenuRef])

  return (
    <>
      <div className="form-input">
        <label>Name</label>
        <ef-text-field placeholder='Name'></ef-text-field>
      </div>
      <div className="form-input">
        <label>Gender</label>
        <div>
          <ef-radio-button name='gender'>Male</ef-radio-button>
          <ef-radio-button name='gender'>Female</ef-radio-button>
          <ef-radio-button name='gender'>Not specific</ef-radio-button>
        </div>
      </div>
      <div className="form-input">
        <label>Date of Birth</label>
        <ef-datetime-picker></ef-datetime-picker>
      </div>
      <div className="form-input">
        <label>Address</label>
        <textarea rows='4' cols='50'></textarea>
      </div>
      <div className="form-input">
        <label>Email</label>
        <ef-email-field placeholder="user@refinitiv.com"></ef-email-field>
      </div>
      <div className="form-input">
        <label>Job Function</label>
        <div id="jobPanel" className="job-panel" role="button" onClick={handleClickJob}>
          <div>{job}</div>
          <ef-icon icon="arrow-down-fill"></ef-icon>
        </div>
        <ef-overlay-menu ref={overlayMenuRef} id="menu">
          <ef-item for="saletrade">Sales & Trading</ef-item>
          <ef-item for="maandcr">M&A and Capital Raising</ef-item>
          <ef-item for="research">Research / Analysis</ef-item>
          </ef-overlay-menu>
        <ef-overlay-menu id="saletrade">
          <ef-item value="Trader">Trader*</ef-item>
          <ef-item value="Sales">Sales*</ef-item>
          <ef-item value="Broker">Broker*</ef-item>
        </ef-overlay-menu>
        <ef-overlay-menu id="maandcr">
          <ef-item value="ECM / DCM - Origination / Syndication">ECM / DCM - Origination / Syndication*</ef-item>
          <ef-item value="M&A / Coverage Banker Senior">M&A / Coverage Banker Senior</ef-item>
          <ef-item value="M&A / Coverage Banker Junior">M&A / Coverage Banker Junior</ef-item>
          <ef-item value="Private Equity / Venture Capital">Private Equity / Venture Capital</ef-item>
          <ef-item value="Investment Banking Business Manager">Investment Banking Business Manager</ef-item>
        </ef-overlay-menu>
        <ef-overlay-menu id="research">
          <ef-item value="Research / Market Analyst">Research / Market Analyst*</ef-item>
          <ef-item value="Quant">Quant</ef-item>
          <ef-item value="Economist">Economist</ef-item>
          <ef-item value="Investment Strategist">Investment Strategist</ef-item>
        </ef-overlay-menu>
      </div>
      <div className="form-input">
        <ef-checkbox>I want to receive news and updates via email</ef-checkbox> 
      </div>
    </>
  )  
}

export default ProfileForm;

// samples/angular/src/app/components/profile-form/profile-form.component.ts
import { Component, OnInit, Input, ViewChild, ElementRef } from '@angular/core';
import { AbstractControl, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-profile-form',
  templateUrl: './profile-form.component.html',
  styleUrls: ['./profile-form.component.less']
})
export class ProfileFormComponent implements OnInit {
  
  @Input() form!: FormGroup;
  @ViewChild('jobPanel') jobPanel!: ElementRef;
  @ViewChild('overlayMenu') overlayMenu!: ElementRef;
  @ViewChild('birthdate') birthdateEle!: ElementRef;
  @ViewChild('genderGroup') genderGroupEle!: ElementRef;
  @ViewChild('letter') mailLetterEle!: ElementRef;
  
  ngOnInit (): void { }

  ngAfterViewInit (): void {
    if (!this.form) {
      return;
    }
    
    this.overlayMenu.nativeElement.parentElement.addEventListener('item-trigger', this.handleJobChange.bind(this));
    this.birthdateEle.nativeElement.addEventListener('value-changed', this.onDateChange.bind(this));
    this.genderGroupEle.nativeElement.addEventListener('checked-changed', this.onGenderChecked.bind(this), true);
    this.mailLetterEle.nativeElement.addEventListener('checked-changed', this.onMailLetterChange.bind(this));
  }

  get name (): AbstractControl | undefined {
    if (!this.form) {
      return;
    }
    return this.form.get('name') as AbstractControl;
  }

  get email (): AbstractControl | undefined {
    if (!this.form) {
      return;
    }
    return this.form.get('email') as AbstractControl;
  }

  get job (): string {
    return this.form.value.job;
  }

  get mailLetter (): boolean {
    return this.form.value.mailLetter;
  }

  onOpenJobMenu (): void {
    if (this.overlayMenu.nativeElement) {
      this.overlayMenu.nativeElement.positionTarget = this.jobPanel.nativeElement;
      this.overlayMenu.nativeElement.opened = true;
    }
  }

  handleJobChange (e: CustomEvent): void {
    const value = e.detail.value;
    if (value) {
      this.overlayMenu.nativeElement.opened = false;
      this.form.patchValue({ job: value });
    }
  }

  onDateChange (e: CustomEvent): void {
    this.form.patchValue({ birthdate: e.detail.value });
  }

  onGenderChecked (e: any): void {
    this.form.patchValue({ gender: e.target?.value });
  }

  onMailLetterChange (e: any): void {
    this.form.patchValue({ mailLetter: e.target.value });
  }
}

<div *ngIf="form">
  <div class="form" [formGroup]="form">
    <div class="form-input">
      <label for="name">Name *</label>
      <ef-text-field
      id="name"
      class="form-field"
      formControlName="name"
      [error]="name && name.invalid && (name.dirty || name.touched)"
      ngDefaultControl></ef-text-field>
    </div>
    <div class="form-input">
      <label id="gender_group">Gender</label>
      <div role="radiogroup" aria-labelledby="gender_group" #genderGroup>
        <ef-radio-button name="gender" value="male" >Male</ef-radio-button>
        <ef-radio-button name="gender" value="female" >Female</ef-radio-button>
        <ef-radio-button name="gender" value="not_disclose" >Prefer not to say</ef-radio-button>
      </div>
    </div>
    <div class="form-input">
      <label for="birthdate">Date of Birth</label>
      <ef-datetime-picker class="form-field" id="birthdate" #birthdate formControlName="birthdate" ngDefaultControl></ef-datetime-picker>
    </div>
    <div class="form-input">
      <label for="address">Address</label>
      <textarea class="form-field" id="address" rows="4" cols="50" formControlName="address"></textarea>
    </div>
    <div class="form-input">
      <label for="email">Email *</label>
      <ef-email-field 
      class="form-field"
      id="email"
      placeholder="user@refinitiv.com"
      formControlName="email"
      [error]="email && email.invalid && (email.dirty || email.touched)"
      ngDefaultControl></ef-email-field>
    </div>
    <div class="form-input">
      <label>Job Function</label>
        <div #jobPanel class="job-panel" role="button" (click)="onOpenJobMenu()">
          <div>{{job}}</div>
          <ef-icon icon="arrow-down-fill"></ef-icon>
        </div>
        <ef-overlay-menu #overlayMenu>
          <ef-item for="saletrade">Sales & Trading</ef-item>
          <ef-item for="maandcr">M&A and Capital Raising</ef-item>
          <ef-item for="research">Research / Analysis</ef-item>
          </ef-overlay-menu>
        <ef-overlay-menu id="saletrade">
          <ef-item value="Trader">Trader*</ef-item>
          <ef-item value="Sales">Sales*</ef-item>
          <ef-item value="Broker">Broker*</ef-item>
        </ef-overlay-menu>
        <ef-overlay-menu id="maandcr">
          <ef-item value="ECM / DCM - Origination / Syndication">ECM / DCM - Origination / Syndication*</ef-item>
          <ef-item value="M&A / Coverage Banker Senior">M&A / Coverage Banker Senior</ef-item>
          <ef-item value="M&A / Coverage Banker Junior">M&A / Coverage Banker Junior</ef-item>
          <ef-item value="Private Equity / Venture Capital">Private Equity / Venture Capital</ef-item>
          <ef-item value="Investment Banking Business Manager">Investment Banking Business Manager</ef-item>
        </ef-overlay-menu>
        <ef-overlay-menu id="research">
          <ef-item value="Research / Market Analyst">Research / Market Analyst*</ef-item>
          <ef-item value="Quant">Quant</ef-item>
          <ef-item value="Economist">Economist</ef-item>
          <ef-item value="Investment Strategist">Investment Strategist</ef-item>
        </ef-overlay-menu>
    </div>
    <div className="form-input">
      <ef-checkbox #letter [checked]="mailLetter">I want to receive news and updates via email</ef-checkbox> 
    </div>
  </div>
</div>
