// samples/react/src/App.js
import React, { useState, useEffect, useRef } from 'react';

import Sidebar from './components/Sidebar';
import Chart from './components/Chart';
import ProfileForm from './components/ProfileForm';

import './styles/lib/App.css';

function App() {
  const dialogRef = useRef(null);

  const [chartType, setChartType] = useState('line');
  const [checked, setChecked] = useState(undefined);

  useEffect(() => {
    const defaultTheme = document.documentElement.getAttribute('theme');
    const isChecked = defaultTheme === 'dark' || undefined;
    setChecked(isChecked);
  },[]);

  const handleClickToggle = (e) => {
    const theme = e.target.checked ? 'dark' : 'light';
    sessionStorage.setItem('elf-theme', theme);
    window.location.reload();
  }

  const handleClickProfileButton = () => {
    if(!dialogRef.current) return;
    dialogRef.current.opened = true;
  }

  return (
    <div className='container'>
      <ef-header level='2' class='toolbar'>
        <div className='toolbar-items' slot='right'>
          Theme:
          <ef-toggle
            class='theme-switcher'
            label='light'
            checked-label='dark'
            checked={checked}
            onClick={handleClickToggle}
          >
          </ef-toggle>
          <ef-button icon='profile' onClick={handleClickProfileButton}></ef-button>
        </div>
      </ef-header>
      <div className="content-container">
        <Sidebar chartType={chartType} setChartType={setChartType}/>
        <Chart chartType={chartType}/>
      </div>
      <ef-dialog ref={dialogRef} header='Edit Profile'>
        <ProfileForm />
      </ef-dialog>
    </div>
  )
}

export default App;

// samples/angular/src/app/app.component.ts
import { Component, ViewChild, ElementRef, OnInit } from '@angular/core';
import { Validators, FormBuilder } from '@angular/forms';
import { data } from '../mock-data';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less']
})
export class AppComponent implements OnInit{
  public loading = true;
  public profileForm = this.fb.group({
    name: ['', Validators.required],
    gender: [''],
    birthdate: [''],
    address: [''],
    email: ['', [Validators.required, Validators.email]],
    job: [''],
    mailLetter: [true]
  });
  public chartType = 'line';
  public checked = false;
  
  public onTabChangeHandler = this.onTabChange.bind(this);

  @ViewChild('chart') chart!: ElementRef;
  @ViewChild('theme') theme!: ElementRef;
  @ViewChild('profile') profileBtn!: ElementRef;
  @ViewChild('dlg') dlg!: ElementRef;
  constructor (private fb: FormBuilder) {}

  async ngOnInit (): Promise<void> {
    const defaultTheme = sessionStorage.getItem('elf-theme') || 'light';
    await this.loadTheme(defaultTheme);
    this.loading = false;
    this.checked = defaultTheme === 'dark';
  }

  ngAfterViewInit (): void {
    this.generateChart();
  }

  loadTheme (theme: string): Promise<unknown> {
    document.documentElement.setAttribute('theme', theme);
    return import(`../themes/${theme}`);
  }

  onTabChange (chartType: string): void {
    this.chartType = chartType;
    this.generateChart();
  }

  generateChart (): void {
    this.chart.nativeElement.config = {
      options: {
        timeScale: {
          timeVisible: true,
          secondsVisible: true
        }
      },
      series: [
        {
          symbol: 'Price',
          type: this.chartType,
          data: data
        }
      ]
    };
  }

  handleThemeToggle (): void {
    const theme = this.theme.nativeElement.checked ? 'dark' : 'light';
    sessionStorage.setItem('elf-theme', theme);
    window.location.reload();
  }

  onOpenProfileDialog (): void {
    this.dlg.nativeElement.opened = true;
  }

  onSaveProfile (): void {
    console.log(this.profileForm.value);
    this.closeDialog();
  }

  closeDialog (): void {
    this.dlg.nativeElement.opened = false;
  }
}

<div class="container" [ngClass]="{'loading': loading}">
  <ef-header class="toolbar" slot="main-header" level="2">
    <div class="toolbar-items" slot="right">
      Theme:
      <ef-toggle
        #theme
        class='theme-switcher'
        label='light'
        checked-label='dark'
        [checked]="checked"
        (click)="handleThemeToggle()">
      </ef-toggle>
      <ef-button #profile icon="profile" (click)="onOpenProfileDialog()"></ef-button>
    </div>
  </ef-header>
  <div class="content-container">
    <app-side-bar [chartType]="chartType" [onTabClickCallback]="onTabChangeHandler"></app-side-bar>
    <div class="chart-container">
      <ef-loader *ngIf="loading"></ef-loader>
      <ef-interactive-chart #chart [ngClass]="{'loading': loading}"></ef-interactive-chart>
    </div>
  </div>

  <ef-dialog #dlg header="Profile">
    <app-profile-form [form]="profileForm"></app-profile-form>
    <div class="form-footer" slot="footer">
      <ef-button id="confirm-btn" cta (click)="onSaveProfile()" [disabled]="profileForm && !profileForm.valid">Confirm</ef-button>
      <ef-button cta (click)="closeDialog()">Cancel</ef-button>
    </div>
  </ef-dialog>
</div>
