// samples/react/src/components/Sidebar.js
import React from 'react'

const Sidebar = ({ chartType, setChartType }) => {
  return (
    <ef-tab-bar vertical>
      <ef-tab
        icon="chart-chartline"
        label="Line Chart"
        active={chartType === 'line' || undefined}
        onClick={() => setChartType('line')}
      >
      </ef-tab>
      <ef-tab
        icon="chart-area"
        label="Area Chart"
        active={chartType === 'area' || undefined}
        onClick={() => setChartType('area')}
      >
      </ef-tab>
      <ef-tab
        icon="chart-bar"
        label="Bar Chart"
        active={chartType === 'bar' || undefined}
        onClick={() => setChartType('bar')}
      >
      </ef-tab>
      <ef-tab
        icon="chart-candles"
        label="Candlestick Chart"
        active={chartType === 'candlestick' || undefined}
        onClick={() => setChartType('candlestick')}
      >
      </ef-tab>
      <ef-tab
        icon="chart-line-bar"
        label="Volume Chart"
        active={chartType === 'volume' || undefined}
        onClick={() => setChartType('volume')}
      >
      </ef-tab>
    </ef-tab-bar>
  )
}

export default Sidebar;

// samples/angular/src/app/components/side-bar/side-bar.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-side-bar',
  templateUrl: './side-bar.component.html',
  styleUrls: ['./side-bar.component.less']
})
export class SideBarComponent implements OnInit {
  @Input()
  chartType!: string;
  
  @Input()
  onTabClickCallback!: (args: any) => void;
  
  ngOnInit (): void {}

  onTabClick (chartType: string): void {
    this.onTabClickCallback(chartType);
  }
}

<ef-tab-bar vertical alignment="left" level="1">
    <ef-tab icon="chart-chartline" label="Line Chart" [active]="chartType === 'line'? 'true': undefined" (click)="onTabClick('line')"></ef-tab>
    <ef-tab icon="chart-area" label="Area Chart" [active]="chartType === 'area'? 'true': undefined" (click)="onTabClick('area')"></ef-tab>
    <ef-tab icon="chart-bars" label="Bar Chart" [active]="chartType === 'bar'? 'true': undefined" (click)="onTabClick('bar')"></ef-tab>
    <ef-tab icon="chart-candles" label="Candlestick Chart" [active]="chartType === 'candlestick'? true: undefined" (click)="onTabClick('candlestick')"></ef-tab>
    <ef-tab icon="chart-line-bar" label="Volume Chart" [active]="chartType === 'volume'? 'true': undefined" (click)="onTabClick('volume')"></ef-tab>
</ef-tab-bar>
